/**
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class Find_the_Difference {
    /* Running time is O(3n), which is a bit slower than using a^b^b=a method. However it is still quilt fast */
    public char findTheDifference(String s, String t) {
        /* The difference of the sum is the addition char ASCII code */
        int ASCII_diff = get_ASCII_sum(t)-get_ASCII_sum(s);
        /* Loop to see which one it is */
        for(char c='a'; c<='z';c++){
            if((int)c-'a'==ASCII_diff)
                return c;
        }
        return 'a';
    }
    /* sum the ASXII code*/
    public int get_ASCII_sum(String s){
        int sum=0;
        for(int i=0;i<s.length();i++){
            sum+=(int)s.charAt(i)-'a';
        }
        return sum;
    }
    public static void main(String[] args){
        String s = "abcd";
        String t = "abcde";

        System.out.print(new Find_the_Difference().findTheDifference(s,t));
    }
}
